### ISSUE TITLE
Chrome web store version no longer works.

### ISSUE THREAD

**Issue by TheW0LVERIN3** [Ugzuzg/gog-owned-on-steam-extension#2]
The chrome version doesn't work. I also tested the firefox version and that one does still work. I hope this is still active and the dev or someone else can fix this.

**Comment by Ugzuzg** [comment]
@TheW0LVERIN3, thanks for reporting. I've sent a new version to be reviewed by the store.

**Comment by Spurlos** [comment]
Excuse me for bringing up this zombie thread, but i don't want to create a separate issue just for a question:

@Ugzuzg Its been a while since MV3 landed on stable Chrome and your extensions has been forcefully disabled because "This extension is no longer available because it doesn't follow best practices for Chrome extensions.".

 Is it possible to update it from your side or should I leave the hopes?

<img width="425" height="229" alt="Image" src="https://github.com/user-attachments/assets/0bd4abac-f5a1-4c3c-bc7f-33775f941cc8" />

**Comment by Ugzuzg** [comment]
I'll have a look. Please open a new issue, though.

**Comment by Ugzuzg** [comment]
@Spurlos, published a new version for Chrome.
